Display error message when moving to missing branch

diff --git a/scripts/bin/git/branch/git-branch-switch b/scripts/bin/git/branch/git-branch-switch
--- a/scripts/bin/git/branch/git-branch-switch
+++ b/scripts/bin/git/branch/git-branch-switch
@@ -22,5 +22,9 @@ for commitRef in $argv; do
   git-dependencies-update $previousCommit
 
   # Stop when we found a matching branch
-  break
+  exit 0
 done
+
+# No matching branch found
+echo "✘ Specified branch not found"
+exit 1
