Updating feature-finish to NOT remove the branch when merging.

diff --git a/scripts/bin/git-feature-finish b/scripts/bin/git-feature-finish
--- a/scripts/bin/git-feature-finish
+++ b/scripts/bin/git-feature-finish
@@ -9,11 +9,11 @@ git merge --squash $branch &>/dev/null
 # Commit with a default message
 git commit -v -m 'Merging of branch '$branch --edit
 # Delete initial branch
-if [[ $? == 0 ]]; then
-	git branch -D $branch
-else
-	echo "Error while commiting, branch $branch is not deleted"
-	echo "Cleaning directory"
-	git reset --hard
-	git clean -fd
-fi
+# if [[ $? == 0 ]]; then
+# 	git branch -D $branch
+# else
+# 	echo "Error while commiting, branch $branch is not deleted"
+# 	echo "Cleaning directory"
+# 	git reset --hard
+# 	git clean -fd
+# fi
