Added js-lint, and added it as a linter

diff --git a/scripts/bin/js/js-lint b/scripts/bin/js/js-lint
--- a/scripts/bin/js/js-lint
+++ b/scripts/bin/js/js-lint
@@ -1,17 +1,39 @@
 #!/usr/bin/env zsh
+# js-lint: Lint a JavaScript file
+# Usage:
+# $ js-lint  ./path/to/file.js       # For CLI
+# $ js-lint -json ./path/to/file.js  # For Vim
+set -x
 
-# Write a zsh script that:
-# - takes one js file as arguments
-# - accepts an optional --json parameter
-#
-# Check where is located the input file by running "yarn-root --force". This
-# will give the path to the project root (where the package.json is)
-#
-# We then check if there is an eslint config file there (either eslint.config.js
-# or .eslintrc.js).
-#
-# - If it has such a config, it use it. Otherwise it should fallback to the
-# config in ~/.oroshi/eslint.config.js
-#
-# It should then run eslint_d on that file, with that config.
-# If --json is passed, it should output the results in json format.
+zparseopts -E -D \
+  -json=flagJson
+isJson=${#flagJson}
+
+# Input file
+inputFile="${1:a}"
+if [[ ! -f "$inputFile" ]]; then
+  echo "Error: File '$inputFile' not found" >&2
+  exit 1
+fi
+
+# Project root
+projectRoot=$(yarn-root ${inputFile:h} --force 2>/dev/null)
+
+# Config file
+configFile=~/.oroshi/eslint.config.js
+if [[ $projectRoot != "" ]]; then
+  [[ -f "$projectRoot/.eslintrc.js" ]] && configFile="$projectRoot/.eslintrc.js"
+  [[ -f "$projectRoot/eslint.config.js" ]] && configFile="$projectRoot/eslint.config.js"
+fi
+
+# Optional args
+formatAsJson=""
+if [[ $isJson -gt 0 ]]; then
+  formatAsJson="--format json"
+fi
+
+# Run eslint_d
+eslint_d \
+  --config "$configFile" \
+  ${=formatAsJson} \
+  "$inputFile"
